= Configuration

== .env-File

The .env file allows you to provide required variables for the local build process. We recommend that you do not check them into your source code management. Ideally, you inject them later via your CI/CD process. If you are already using the CCD pipeline from Crownpeak Technology, we will do this for you automatically.

=== FSXA_API_KEY `string`

This API key is required by the PWA to obtain authorized access to the CaaS and navigation service. Our Customer Success Management team (team-csm@e-spirit.com) will be happy to provide you with this key after the successful provisioning of your FSXA environment.

=== FSXA_CAAS `string`

The URL under which the CaaS can be reached. This URL is only used on the server and is not visible to the user in the client.

=== FSXA_NAVIGATION_SERVICE `string`

The URL under which the navigation service is available. This URL is only used on the server and is not visible to the user in the client.

=== FSXA_PROJECT_ID `string`

Several projects can be configured on your FirstSpirit server. In order for the PWA to know which data it needs to access, it needs the UUID of the relevant project.

For the project(s) provided by Crownpeak Technology you will be given this data too.

For other projects you can look at _Project Properties_ in _ServerManager_, then _Project Components_, then _CaaS Connect Project App_.

Another way to access the project_id is by https://docs.e-spirit.com/odfs/template-develo/scripting/making-scripts/[adding the following script]:

....
import de.espirit.firstspirit.agency.OperationAgent;
import de.espirit.firstspirit.ui.operations.RequestOperation;

message = context.requireSpecialist(OperationAgent.TYPE).getOperation(RequestOperation.TYPE);
message.setTitle("Project UUID");
message.setKind(RequestOperation.Kind.INFO);
message.perform("Project UUID: " + context.project.uuid);
....

Use the following _display logic_ to only make the script menu entry visible to project admins:

....
connection = context.userService.connection;
return connection.user.isProjectAdmin(connection.project);
....

=== FSXA_TENANT_ID `string`

The tenantId is used by the PWA to distinguish between the different FSXA environments provided to you.

=== FSXA_MODE `"preview"` | `"release"`

We distinguish between preview and release data. This is the traditional FirstSpirit way. Specify here which data should be loaded by the PWA.

=== BASE_URL `string` (optional but recommended)

Default is set to `http://localhost:3000`.

=== FSXA_SNAP_URL `string`  (optional but recommended) 

FSXA offers a lot of LiveEdit features in the authoring environment to edit sections, images, datasets, etc. in place and this needs an external dependency called Snap Library.

The current implementation is https://docs.e-spirit.com/tpp/snap/[TPP Snap] and the URL to this script has to look like:

`https://[your-firstspirit-server]/fs5webedit/snap.js` or `https://[your-firstspirit-server]/fs5webedit[_project-id]/snap.js`

where [your-firstspirit-server] is the hostname of your FirstSpirit server, e.g. https://company.e-spirit.hosting and fs5webedit[_project-id] the path of the ContentCreator WebApp (just log in to your project in ContentCreator to see the path in your browser).

This path should be set as `FSXA_SNAP_URL`` in your .env file. A fallback is the latest https://cdn.jsdelivr.net/npm/fs-tpp-api/snap.js[CDN version] of this dependency, which may cause a version mismatch and is not recommended.

=== FSXA_LOG_LEVEL `number` _optional_

Possible log levels: `0` = Info, `1` = Log, `2` = Warning, `3` = Error, `4` = None. The default is `3`.

You can also set the `logLevel` via _app.config.ts_

ENV variable will take the priority if set, e.x. 

=== FSXA_MAX_REFERENCE_DEPTH `number` _optional_

Due to performance reasons content references in your project get resolved up to a maximum reference depth of 10. Meaning a dataset refering to a dataset refering to a dataset ... and so on. You can increase that number by specifying the `FSXA_MAX_REFERENCE_DEPTH` variable.

=== FSXA_ENABLE_EVENT_STREAM `boolean` _optional_

When enabled, events for `insert`, `replace` and `delete` CaaS documents can be observed and handled. It's currently used in preview mode, to sync updated data in FirstSpirit with the CaaS and the App State.

== app.config.ts file

The following settings allow easy configuration of the PWA through the `app.config.ts` file. Keep in mind that changes to the configuration of this file will be checked into version control.


=== defaultLocale `string`

Normally the current URL is used to find out the language. If this is not possible (for example, when a user calls `/`) the `defaultLocale` is used to retrieve the navigation data via the `FSXA API`. This property is required.

=== devMode `boolean` _optional_

The `DevMode` helps you to quickly build new components or adapt existing ones. See xref:GettingStarted/MyFirstTemplate.adoc[Getting Started] for screenshots and more details.

==== logLevel `number` _optional_

Possible log levels: `0` = Info, `1` = Log, `2` = Warning, `3` = Error, `4` = None. The default is `3`.

You can also set the `logLevel` via _ENV variable_

ENV variable will take the priority if set, e.x. *FSXA_LOG_LEVEL*=`3`


=== enableEventStream _optional_

When enabled, events for `insert`, `replace` and `delete` CaaS documents can be observed and handled. It's currently used in preview mode, to sync updated data in FirstSpirit with the CaaS and the App State.


=== example app.config.ts

[source,javascript]
----
const fsxaConfig = {
  logLevel: LogLevel.NONE,
  devMode: false,
  defaultLocale: "de_DE",
  enableEventStream: false,
}

export default defineAppConfig(fsxaConfig);
----
