= Composables

In Vue 3 applications link:https://vuejs.org/guide/reusability/composables.html[composables] are used to encapsulate and reuse stateful logic. We use composables here to handle

* localization settings,
* navigation data,
* page content,
* and project properties.


For in depth information on how to use composables in your Nuxt project check out the official link:https://nuxt.com/docs/guide/directory-structure/composables[Nuxt documentation on composables].

== Locale

The locale composable (`~/composables/locale.ts`) is used to handle the localization state of the PWA. First, you can define the available locales in static config:

[source, typescript]
const defaultConfig: LocaleConfig = {
  activeLocale: undefined,
  defaultLocale: "de_DE",
  allLocales: getAllLocales(),
};

`getAllLocales` returns a hard-coded string array (`['de_DE', 'en_GB']`) as default, but can be implemented to dynamically fetch available languages from the CaaS.

The composable can be imported in any component to read or set the locale:

[source, javascript]
<script setup lang="ts">
const { config, setLocale } = useLocale();
</script>

The config contains the active locale, the default locale, as well as all possible locales. `setLocale` can be used to implement a language switch component (`~/components/AppLayout/LanguageSwitch.vue`). After setting the locale, both the content and navigation data get refetched. It is possible that the current active route does not have a corresponding route in the selected language, which will result in a TODO.

== Navigation Data


The navigation data provided by the Navigation Service can be accessed through `useNavigation` (`~/composables/navigation.ts`). This composable can be used to get or set the `activeNavigationItem`, which is further described in the xref:Routing.adoc[routing documentation] or shown in `~/components/InternalLink.vue`.

[source, javascript]
const { setActiveNavigationItem } = useNavigationData();

You can also access the raw `navigationData` of type `NavigationData` to render the navigation tree, as shown in `~/components/AppLayout/Navigation.vue`.

[source, javascript]
const { navigationData } = useNavigationData();

The index route / is handled separately in the Navigation Service and the corresponding route can be accessed with `getIndexRoute()`.

== Content
The CaaS content of the current route can be accessed by using the `useContent` (`~/composables/content.ts`) composable.

[source, javascript]
const { content: page } = useContent();

The `content` is of type `Page` and contains everything that is required to render the content. It might be null in the beginning or on an invalid route.

The content changes automatically on route changes and is reactive.

== Project Properties
Project properties are accessed by using the `useProjectProperties` (`~/composables/projectProperties.ts`) composable.

[source, javascript]
const { projectProperties } = useProjectProperties();

The content changes automatically on route locale changes and is reactive. 

For more information about what project properties are and how to work with them read xref:docs/modules/ROOT/pages/ProjectProperties.adoc[this short guide].