= TPP-Snap

TPP-Snap from the https://docs.e-spirit.com/tpp/index.html.en[OmnichannelManager] is a JavaScript library designed to connect the FirstSpirit ContentCreator UI with dynamically generated HTML elements (like in a PWA). This connection is achieved using preview ids. When you add a known preview id as an attribute to an HTML element the Snap library will automatically decorate it using borders and buttons when your PWA is viewed in the FirstSpirit ContentCreator. This allows editors to edit the contents of dynamically generated HTML Elements. The library also offers the tools to add your own buttons to the UI as you see fit. To enable this functionality, you MUST set the environment variable FSXA_MODE to "preview".

There are some configurations you could customize, like the used xref:Configuration.adoc#fsxa_snap_url-string[version] and xref:Configuration.adoc#firstspirit-omnichannel-manager-api-version[event-hooks].

== Nested Elements

At layout and section level, the FSXA takes care of enriching the UI so that the elements are editable in the ContentCreator. However, as soon as we have sections within a dataset or a section, there is currently no automatism. So you have to take action here that your child sections can also be edited in the ContentCreator.

To enable the editing of such a component make sure to provide a custom preview id for both the nested component as well as the parent component using the syntax #PARENT_COMPONENT_NAME and #NESTED_COMPONENT_INDEX as the following examples show. The example is a snippet from the InterestingFacts component

=== Example

[source,xml]
----
<template>
    <div
      class="grid grid-cols-3 gap-6"
      data-preview-id="#st_counters"
      data-inedit
    >
      <div
        v-for="(counter, index) in data.st_counters"
        :key="counter.id"
        :data-preview-id="`#${index}`"
      >
        <div
          class="text-4xl font-bold text-yellow-500"
          data-inedit
          data-preview-id="#st_number"
        >
          {{ counter.data.st_number }}
        </div>
        <div class="border-t-2 text-gray-300" data-preview-id="#st_text">
          {{ counter.data.st_text }}
        </div>
      </div>
    </div>
</template>

----

Further information can be found in the documentation for the https://docs.e-spirit.com/tpp/snap/index.html#nested-components[TPP-Snap] library, which is automatically integrated in the preview mode and enables these functionalities.


== TPP_SNAP Hooks

The communication between the application itself and the editor is done via hooks. These hooks are event listeners that can be registered and implemented in the tpp client plugin (`~/plugins/3.tpp.client.ts`). This plugin is already implementing the minimum required hooks to make the TPP-Snap library work. However, you can implement your own hooks to extend the functionality of the TPP-Snap library.
Currently, 3 hooks are implemented:

1. onRequestPreviewElement: This hook is called for example when the user selects a page in the editor search bar. This is the hook that is mainly responsible for the navigation

2. onRerenderView: This hook updates the content (both dataset and page) if the user changed something in the editor. This hooks also waits for the CaaS events to make sure that the update is completed before trying to fetch content. This is possible, because the hook is called before the CaaS even starts writing the content to the database.

3. onNavigationChange: This hook is called when a new page is added, deleted or the navigation structure changes in any other way. It is possible that both the onRequestPreviewElement and onNavigationChange hook is called when a new page is added, making it important to only handle that case in one of the hooks.

4. onContentChange: This is a hook that has NOT been implemented and is not required. onContentChange gets claled before onRerenderView and provides both the previewId, the DOM node and the changed content. This can allow you to skip the data fetching done in onRerenderView and instead update the DOM node directly. However, this is just a small optimization and is not required.

== CaaS Events

CaaS events are sent on every change to your CaaS database and sent as a webhook to the Nuxt Server. The Websocket gets initiated in `~/server/middleware/websocket.ts`, stored in `~/server/WebsocketSingleton.ts` and used in `~/server/api/[endpoint].get.ts`. The communication between the Nuxt server and frontend is also defined in the endpoint and is done over EventStreams. This logic is mostly handled by the TPP_SNAP library, the rest can be found in `~/utils/tpp.ts`, specifically the `waitForPreviewId` function. CaasEvents are also optional, instead of waiting for the event a well timed timeout can be used to make sure that the content is updated before the application tries to fetch it.