#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

echo "branch: $branch"
echo "CI: $CI"

if [ "$branch" = "main" -a "$CI" != 1 ]; then
  echo "You can't commit directly to main branch"
  exit 1
fi

if [ "$branch" = "alpha" -a "$CI" != 1 ]; then
  echo "You can't commit directly to alpha branch"
  exit 1
fi

